### PR TITLE
Add retries to Turbinia API download calls

### PR DESCRIPTION
**Pull request by jleaniz**
Retry Turbinia API calls if they fail when downloading Turbinia task output.

### CODE REVIEW

**Comment by tomchop** [comment]
LGTM! Could you just fix the mypy errors please?

**Comment by jleaniz** [comment]
> LGTM! Could you just fix the mypy errors please?

Done

**Comment by jleaniz** [comment]
@tomchop good with this?

**Comment by tomchop** [comment]
Yes! Merged

**Pull request merged**
