### PR TITLE
Update lock file

### PR DESCRIPTION
**Pull request by tomchop**

### CODE REVIEW

**Comment by ramo-j** [comment]
Drive by comment - Is it possible to get an update to libcloudforensics in here as well? I've recently made changes there that would be good to get in DFTW, though have been having trouble managing conflicting deps.

**Review by jleaniz — DISMISSED** [review]
LGTM

**Comment by tomchop** [comment]
I'm gonna try to resolve some LCF dependency conflicts before merging

**Comment by tomchop** [comment]
Turns out this is not as straightofrward as it seems. poetry barfs on trying to install the latest lcf with an obscure error message. If I upgrade the LCF version using pip, I get some errors:

```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/dftimewolf-9TtSrW0h-py3.11/lib/python3.11/site-packages/mock/mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tests/lib/collectors/azure.py", line 249, in testFindDisksToCopy
    azure_collector.SetUp(
  File "/app/dftimewolf/lib/collectors/azure.py", line 178, in SetUp
    self.analysis_vm, _ = az_forensics.StartAnalysisVm(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/dftimewolf-9TtSrW0h-py3.11/lib/python3.11/site-packages/libcloudforensics/providers/azure/forensics.py", line 185, in StartAnalysisVm
    analysis_vm, created = az_account.compute.GetOrCreateAnalysisVm(
                           ^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/dftimewolf-9TtSrW0h-py3.11/lib/python3.11/site-packages/libcloudforensics/providers/azure/internal/account.py", line 81, in compute
    self._compute = compute_module.AZCompute(self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/dftimewolf-9TtSrW0h-py3.11/lib/python3.11/site-packages/libcloudforensics/providers/azure/internal/compute.py", line 75, in __init__
    capacity_provider = resource_client.providers.get('Microsoft.Capacity')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/dftimewolf-9TtSrW0h-py3.11/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/dftimewolf-9TtSrW0h-py3.11/lib/python3.11/site-packages/azure/mgmt/resource/resources/v2022_09_01/operations/_operations.py", line 8991, in get
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidSubscriptionId) The provided subscription identifier 'fake-subscription-id' is malformed or invalid.
Code: InvalidSubscriptionId
Message: The provided subscription identifier 'fake-subscription-id' is malformed or invalid.
```

**Comment by tomchop** [comment]
The linter checks are failing because we upgraded pylint from 2.x to 3.x; will tackle in a separate PR: https://github.com/log2timeline/dftimewolf/issues/862

**Comment by tomchop** [comment]
Also, managed to get LCF latest to work! So that's good news.

**Review by Fryyyyy — APPROVED** [review]

**Pull request merged**
