### PR TITLE
Updated default artifact names

### PR DESCRIPTION
**Pull request by binglot**
The "ForensicArtifacts" repo has been gradually updated and a lot of the names have changed, updating the list in the GRR Artifact Collector class.

### CODE REVIEW

**Comment by binglot** [comment]
Setting this up as a Draft for now, until the GRR instance has been updated with the latest artifact definitions.

**Comment by binglot** [comment]
@tomchop @ramo-j - FYI

**Comment by binglot** [comment]
Are the test errors caused by me?

**Comment by sydp** [comment]
> Are the test errors caused by me?

Yeah change the GrrSetUp function signature back to what is at HEAD and it should be ok.

**Comment by binglot** [comment]
> > Are the test errors caused by me?
> 
> Yeah change the GrrSetUp function signature back to what is at HEAD and it should be ok.
> 
> ```
> dftimewolf/lib/collectors/grr_hosts.py:87: error: Missing positional argument "message_callback" in call to "GrrSetUp" of "GRRBaseModule"
> ```

Good catch @sydp ! I didn't realise that something else besides the list of artifacts was also changed. Thanks :)

**Comment by binglot** [comment]
Ready for review, please :) @ramo-j @tomchop

**Comment by ramo-j** [comment]
For the purposes of a review, where would I look in google/grr to confirm the artefact list?

**Comment by binglot** [comment]
> For the purposes of a review, where would I look in https://github.com/google/grr/ to confirm the artefact list?

I missed this comment, you can find the latest recipes here: https://github.com/ForensicArtifacts/artifacts/tree/main/data

**Review by ramo-j — APPROVED** [review]
LGTM. we should make sure this is included in any changes in #582

**Pull request merged**
